// Generated by CoffeeScript 1.3.3
var Blur, Rendernode;

Rendernode = require('/rendernode');

return Blur = (function() {

  function Blur(gl, _arg) {
    var filter, height, type, width;
    width = _arg.width, height = _arg.height, type = _arg.type, filter = _arg.filter;
    if (type == null) {
      type = gl.UNSIGNED_BYTE;
    }
    if (filter == null) {
      filter = 'linear';
    }
    this.output = new Rendernode(gl, {
      width: width,
      height: height,
      program: get('blur.shader'),
      drawable: quad,
      filter: filter,
      type: type
    });
  }

  Blur.prototype.update = function(source) {
    return this.output.start().sampler('source', source).draw().end();
  };

  Blur.prototype.resize = function(width, height) {
    return this.output.resize(width, height);
  };

  return Blur;

})();
