// Generated by CoffeeScript 1.3.3
var Plane,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

return Plane = (function(_super) {

  __extends(Plane, _super);

  Plane.prototype.attribs = ['position', 'normal', 'texcoord'];

  function Plane(gl, s) {
    var vertices;
    this.gl = gl;
    if (s == null) {
      s = 1;
    }
    Plane.__super__.constructor.call(this);
    this.size = 6;
    vertices = [-s, 0, -s, 0, 1, 0, 0, 0, -s, 0, s, 0, 1, 0, 0, 1, s, 0, s, 0, 1, 0, 1, 1, s, 0, -s, 0, 1, 0, 1, 0, -s, 0, -s, 0, 1, 0, 0, 0, s, 0, s, 0, 1, 0, 1, 1];
    this.uploadList(vertices);
  }

  Plane.prototype.setPointersForShader = function(shader) {
    this.gl.bindBuffer(this.gl.ARRAY_BUFFER, this.buffer);
    this.setPointer(shader, 'position', 3, 0, 8);
    this.setPointer(shader, 'normal', 3, 3, 8);
    this.setPointer(shader, 'texcoord', 2, 6, 8);
    return this;
  };

  return Plane;

})(require('drawable'));
