// Generated by CoffeeScript 1.3.3
var Emitter;

return Emitter = (function() {

  function Emitter() {
    this.handlers = {};
  }

  Emitter.prototype.on = function(name, callback) {
    var handlers;
    handlers = this.handlers[name];
    if (handlers === void 0) {
      handlers = this.handlers[name] = [];
    }
    handlers.push(callback);
    return this;
  };

  Emitter.prototype.trigger = function(name, a1, a2, a3, a4, a5, a6) {
    var handler, handlers, _i, _len;
    handlers = this.handlers[name];
    if (handlers !== void 0) {
      for (_i = 0, _len = handlers.length; _i < _len; _i++) {
        handler = handlers[_i];
        handler(a1, a2, a3, a4, a5, a6);
      }
    }
    return this;
  };

  return Emitter;

})();
