// Generated by CoffeeScript 1.3.3
var bar, container, hidden, label, loading, makeBar, ui;

ui = $('#ui');

hidden = true;

container = $('<div></div>').css({
  position: 'absolute',
  top: '50%',
  left: '50%',
  width: 200,
  height: 40,
  marginLeft: -100,
  marginTop: -20
});

label = $('<div></div>').appendTo(container).css({
  position: 'absolute',
  top: 0,
  left: 0,
  width: 200,
  height: 20,
  textAlign: 'center',
  color: 'white'
});

loading = $('<div></div>').appendTo(container).css({
  position: 'absolute',
  top: 20,
  left: 0,
  width: 200,
  height: 20,
  border: '1px solid white'
});

bar = null;

makeBar = function() {
  loading.empty();
  return bar = $('<div></div>').appendTo(loading).css({
    position: 'absolute',
    top: 0,
    left: 0,
    width: 0,
    height: 20,
    backgroundColor: 'white',
    '-webkit-transition': 'width 0.7s'
  });
};

exports.show = function(text) {
  label.text(text);
  makeBar();
  return container.fadeIn('slow').appendTo(ui);
};

exports.hide = function() {
  return container.fadeOut('slow', function() {
    return container.detach();
  });
};

exports.progress = function(factor) {
  return bar.width(factor * 200);
};
