// Generated by CoffeeScript 1.3.3

exports.run = function(callback) {
  var last, step;
  last = gettime();
  step = function() {
    var current, delta;
    current = gettime();
    delta = current - last;
    last = current;
    callback(current, delta);
    return requestAnimationFrame(step);
  };
  return requestAnimationFrame(step);
};
