// Generated by CoffeeScript 1.3.3
var AntiAlias, Quad, Rendernode;

Rendernode = require('/rendernode');

Quad = require('/webgl/quad');

return AntiAlias = (function() {

  function AntiAlias(gl, gui, source) {
    var folder;
    this.gl = gl;
    this.source = source;
    gui.remember(this);
    this.node = new Rendernode(this.gl, {
      program: get('fxaa3_11.shader'),
      drawable: quad
    });
    this.subpixel_aa = 0.75;
    this.contrast_treshold = 0.166;
    this.edge_treshold = 0.0;
    folder = gui.addFolder('Antialias');
    folder.add(this, 'subpixel_aa', 0.0, 1.0).name('Subpixel aa');
    folder.add(this, 'contrast_treshold', 0.063, 0.333).name('Contrast Treshold');
    folder.add(this, 'edge_treshold', 0.0, 0.0833).name('Edge Treshold');
  }

  AntiAlias.prototype.apply = function() {
    return this.node.start().f('subpixel_aa', this.subpixel_aa).f('contrast_treshold', this.contrast_treshold).f('edge_treshold', this.edge_treshold).clear().sampler('source', this.source).draw().end();
  };

  AntiAlias.prototype.resize = function(width, height) {
    return this.node.resize(width, height);
  };

  return AntiAlias;

})();
