// Generated by CoffeeScript 1.3.3
var Sun,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

return Sun = (function(_super) {

  __extends(Sun, _super);

  function Sun(gui, orientation, elevation) {
    var folder;
    this.orientation = orientation != null ? orientation : 104;
    this.elevation = elevation != null ? elevation : 60;
    this.update = __bind(this.update, this);

    gui.remember(this);
    Sun.__super__.constructor.call(this);
    folder = gui.addFolder('Sun');
    folder.add(this, 'orientation', 0, 360).onChange(this.update);
    folder.add(this, 'elevation', 0, 90).onChange(this.update);
    this.near = -1;
    this.far = 41;
    this.proj = new Mat4().ortho(this.near, this.far, 21, -21, -21, 21);
    this.view = new Mat4();
    this.rot = new Mat3();
    this.update();
  }

  Sun.prototype.update = function() {
    this.view.identity().translateVal3(0, 0, -21).rotatex(this.elevation).rotatey(this.orientation).translateVal3(0, -7.5, 0).toMat3(this.rot.identity());
    this.trigger('change');
    return this;
  };

  return Sun;

})(require('events'));
